---
title: "00 Project Setup"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---
<style>
    body .main-container {
        max-width: 100%;
    }
</style>

This file specifies dependencies in with packrat.

```{r}
# install.packages('packrat', dependencies=T)
# library(packrat)
# 
# packrat::init(project = paste0(here::here(), "/packrat"))

```



```{r}

install.packages('knitr', dependencies=T)
install.packages('devtools', dependencies=T)
devtools::install_github("tidyverse/ggplot2") # geom_sf requires ggplot installed off of the dev server
install.packages('tidyverse', dependencies=T)
install.packages('data.table', dependencies=T)
install.packages('sf', dependencies=T)
install.packages('caTools', dependencies=T)
install.packages('xgboost', dependencies=T)
install.packages('pacman', dependencies=T)
install.packages('units', dependencies=T)
install.packages('date', dependencies=T)
install.packages('car', dependencies=T)
install.packages('strigr', dependencies=T)
install.packages('cowplot', dependencies=T)
install.packages('ggjoy', dependencies=T)
install.packages('party', dependencies=T)
install.packages('Metrics', dependencies=T)
install.packages('MLmetrics', dependencies=T)
install.packages('precrec', dependencies=T)
install.packages('dummies', dependencies=T)
install.packages('janitor', dependencies=T)
install.packages('DT', dependencies=T)
install.packages('ggmap', dependencies=T)
install.packages('mosaic', dependencies=T)
install.packages('ggformula', dependencies=T)
install.packages('magrittr', dependencies=T)
install.packages('glue', dependencies=T)
install.packages('RANN', dependencies=T)
install.packages('re2r', dependencies=T)
install.packages('dummy', dependencies=T)
install.packages('doParallel', dependencies=T)
install.packages('quanteda', dependencies=T)
install.packages('ggrepel', dependencies=T)
install.packages('dissUtils', dependencies=T)
install.packages('stringi', dependencies=T)
install.packages('xtable', dependencies=T)
install.packages('SnowballC', dependencies=T)
install.packages('xtable', dependencies=T)
install.packages('tools', dependencies=T)
install.packages('lubridate', dependencies=T)
install.packages('digest', dependencies=T)
install.packages('rgdal', dependencies=T)
install.packages('stringr', dependencies=T)
install.packages('foreach', dependencies=T)
install.packages('pinp', dependencies=T)

devtools::document()

#library("miniCRAN")
#tags <- "MeasuringLandscape"
#pkgDep(tags, availPkgs = cranJuly2014)

require(devtools)
#install_version("backports", version = "1.1.0")
#library(backports)

```
