---
title: "Recall and Accuracy"
author: "Rex W. Douglass"
date: "12/5/2016"
output: 
  html_notebook:
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: inline
---


```{r, results='hide', message=FALSE, warning=FALSE }
# !diagnostics off
library(MeasuringLandscapeCivilWar)
devtools::load_all()
dir_figures <- glue(getwd(), "/../paper/figures/")

gc()

knitr::opts_knit$set(progress = TRUE, verbose = TRUE)
knitr::opts_chunk$set(fig.width=12, fig.height=8,  warning=FALSE, message=FALSE, cache=TRUE)
options(width = 160)

```


```{r}

#Load Events
events_sf <- readRDS(system.file("extdata", "events_sf.Rdata", package = "MeasuringLandscapeCivilWar")) 

events_sf_text_coord_unique <- ddply(events_sf[,c('location_text','name_clean','name_cleaner','document_district_clean','map_coordinate_clean_latitude','map_coordinate_clean_longitude')],
                                     .(location_text), transform,
      map_coordinate_has =sum(!is.na(map_coordinate_clean_latitude))
      )


#Reload from scratch each time in case we subset sometehing weirdly
georef_all_dt <- readRDS(system.file("extdata", "georef_all_dt.Rds", package = "MeasuringLandscapeCivilWar")) 

table(events_sf$name_cleaner %in% georef_all_dt$name_cleaner) #All events are in here
table(events_sf$name_cleaner %in% georef_all_dt$name_cleaner[!is.na(georef_all_dt$georef_b)]) #7,742 events with at least one gazeteer suggestion

#Exclude all distance = 0 obs, those are self matches
georef_all_dt <- subset(georef_all_dt, 
                        !is.na(name_cleaner) & # must have a name
                        (is.na(distance_km) | distance_km!=0)  ) #Can be either missing or not zero. Only thing we drop is zero because that's a self match
```


# Predict missing coordinates

Proof of concept, show works on original missingness


```{r}

#Military coordinates only
pred_cords <- predict_missingness_dv(!is.na(events_sf$map_coordinate_clean_latitude))
auc_cords_dataset <- Metrics::auc(pred_cords$label, pred_cords$xb)
recall_cords_dataset <- sum(pred_cords$label)

#Text only
pred_text <- predict_missingness_dv(!is.na(events_sf$name_cleaner))
auc_text_dataset <- Metrics::auc(pred_text$label, pred_text$xb)
recall_text_dataset <- sum(pred_text$label)

#Military or Text
pred_cordstext <- predict_missingness_dv(!is.na(events_sf$name_cleaner) | !is.na(events_sf$map_coordinate_clean_latitude))
auc_cordstext_dataset <- Metrics::auc(pred_cordstext$label, pred_cordstext$xb)
recall_cordstext_dataset <- sum(pred_cordstext$label)


#Hand Rule
setkey(georef_all_dt, handrule)
georef_all_dt_handrule <- georef_all_dt[,.SD[1], by=list(event_hash) ]
pred_source_handrule <- predict_missingness_dv(events_sf$event_hash %in% georef_all_dt_handrule$event_hash)
auc_handrule_dataset <- Metrics::auc(pred_source_handrule$label, pred_source_handrule$xb)
recall_handrule_dataset <- sum(pred_source_handrule$label)

#Ensemble Rule
setkey(georef_all_dt, rule_ensemble)
georef_all_dt_ensemble <- georef_all_dt[,.SD[1], by=list(event_hash) ]
pred_source_ensemble <- predict_missingness_dv(events_sf$event_hash %in% georef_all_dt_ensemble$event_hash)
auc_ensemble_dataset <- Metrics::auc(pred_source_ensemble$label, pred_source_ensemble$xb)
recall_ensemble_dataset <- sum(pred_source_ensemble$label)


#Source dataset
georef_all_dt_bysource <- georef_all_dt[,list(distance_km_min=min(distance_km, na.rm=T) ),by=list(event_hash, source_dataset)] ; dim(georef_all_dt_bysource)
georef_all_dt_bysource[!is.finite(distance_km_min), distance_km_min:=NA]
pred_source_dataset_list <- list()
for( q in na.omit(unique(georef_all_dt_bysource$source_dataset)) ){
  print(q)
  pred_source_dataset_list[[as.character(q)]] <- predict_missingness_dv(events_sf$event_hash %in% georef_all_dt_bysource[source_dataset==q & !is.na(distance_km_min)]$event_hash)
}
auc_source_dataset <- sapply(pred_source_dataset_list, FUN=function(q) Metrics::auc(q$label, q$xb))
recall_source_dataset <- sapply(pred_source_dataset_list, FUN=function(q) sum(q$label) )



#fuzzy
georef_all_dt_byfuzzy <- georef_all_dt[,list(distance_km_min=min(distance_km, na.rm=T) ),by=list(event_hash, fuzzy)] ; dim(georef_all_dt_bysource)
georef_all_dt_byfuzzy[!is.finite(distance_km_min), distance_km_min:=NA]
pred_fuzzy_list <- list()
for( q in na.omit(unique(georef_all_dt_byfuzzy$fuzzy)) ){
  print(q)
  pred_fuzzy_list[[as.character(q)]] <- predict_missingness_dv(events_sf$event_hash %in% georef_all_dt_byfuzzy[fuzzy==q & !is.na(distance_km_min)]$event_hash)
}
auc_fuzzy <- sapply(pred_fuzzy_list, FUN=function(q) Metrics::auc(q$label, q$xb))
recall_fuzzy <- sapply(pred_fuzzy_list, FUN=function(q) sum(q$label) )
bias_df <- rbindlist(list(
    cbind(auc=auc_fuzzy, recall=recall_fuzzy) %>% data.frame() %>% rownames_to_column("label") %>% mutate(Type="Fuzzy"),
    cbind(auc=auc_source_dataset, recall=recall_source_dataset) %>% data.frame() %>% rownames_to_column("label") %>% mutate(Type="Source Dataset") 
))

#geometry_type
georef_all_dt_bygeometry_type <- georef_all_dt[,list(distance_km_min=min(distance_km, na.rm=T) ),by=list(event_hash, geometry_type)] 
georef_all_dt_bygeometry_type[!is.finite(distance_km_min), distance_km_min:=NA]
pred_geometry_type_list <- list()
for( q in na.omit(unique(georef_all_dt_bygeometry_type$geometry_type)) ){
  print(q)
  pred_geometry_type_list[[as.character(q)]] <- predict_missingness_dv(events_sf$event_hash %in% georef_all_dt_bygeometry_type[geometry_type==q & !is.na(distance_km_min)]$event_hash)
}
auc_geometry_type <- sapply(pred_geometry_type_list, FUN=function(q) Metrics::auc(q$label, q$xb))
recall_geometry_type <- sapply(pred_geometry_type_list, FUN=function(q) sum(q$label) )

#Self Reference
georef_all_dt_byselfreference <- georef_all_dt[,list(distance_km_min=min(distance_km, na.rm=T) ),by=list(event_hash, SelfReference )] ; dim(georef_all_dt_bysource)
georef_all_dt_byselfreference[!is.finite(distance_km_min), distance_km_min:=NA]
pred_selfreference_list <- list()
for( q in na.omit(unique(georef_all_dt_byselfreference$SelfReference)) ){
  print(q)
  pred_selfreference_list[[as.character(q)]] <- predict_missingness_dv(events_sf$event_hash %in% georef_all_dt_byselfreference[SelfReference==q & !is.na(distance_km_min)]$event_hash)
}
auc_selfreference <- sapply(pred_selfreference_list, FUN=function(q) Metrics::auc(q$label, q$xb))
recall_selfreference <- sapply(pred_selfreference_list, FUN=function(q) sum(q$label) )



bias_dv_df <- rbindlist(list(
    cbind(auc=auc_cords_dataset, recall=recall_cords_dataset) %>% data.frame() %>% rownames_to_column("label") %>% 
      mutate(label="Original Coords") %>% mutate(Type="Original Geo Info"),

    cbind(auc=auc_text_dataset, recall=recall_text_dataset) %>% data.frame() %>% rownames_to_column("label") %>% 
      mutate(label="Original Text") %>% mutate(Type="Original Geo Info"),
    cbind(auc=auc_cordstext_dataset, recall=recall_cordstext_dataset) %>% data.frame() %>% rownames_to_column("label") %>% 
      mutate(label="Original Coords or Text") %>% mutate(Type="Original Geo Info"),

    cbind(auc=auc_cordstext_dataset, recall=recall_cordstext_dataset) %>% data.frame() %>% rownames_to_column("label") %>% 
      mutate(label="Hand Rule") %>% mutate(Type="Rule"),
    cbind(auc=auc_cordstext_dataset, recall=recall_cordstext_dataset) %>% data.frame() %>% rownames_to_column("label") %>% 
      mutate(label="Ensemble Rule") %>% mutate(Type="Rule"),
        
    cbind(auc=auc_selfreference, recall=recall_selfreference) %>% data.frame() %>% rownames_to_column("label") %>% mutate(label=ifelse(label, "Match to Other Events","No Match to Other Events")) %>% 
                        mutate(Type="Allow Match To Other Events"),
    cbind(auc=auc_fuzzy, recall=recall_fuzzy) %>% data.frame() %>% rownames_to_column("label") %>% mutate(label=ifelse(label, "Fuzzy","Exact")) %>% mutate(Type="Match Type"),
    cbind(auc=auc_source_dataset, recall=recall_source_dataset) %>% data.frame() %>% rownames_to_column("label") %>% mutate(Type="Source Dataset"),
    cbind(auc=auc_geometry_type, recall=recall_geometry_type) %>% data.frame() %>% rownames_to_column("label") %>% mutate(Type="Geometry Type")
))

colours = c("Allow Match To Other Events" = "#F8766D",
            "Geometry Type" = "#A3A500",
            "Match Type" = "#00BF7D",
            "Rule" = "#00B0F6",
            "Source Dataset"="#E76BF3",
            "Original Geo Info"="#53B400") 

p_load(ggrepel, tools)
p_bias_dv <- bias_dv_df %>% ggplot(aes(x= auc,
             y= round(recall/nrow(events_sf),2) , label=label, col=Type)) + geom_text_repel(size=3) + theme_bw() +
           xlab("Predictability of Missingness (Area Under the Curve)") + ylab("Recall Ratio") +
           #ggtitle("Structual Missingness in Terms of Outcomes by Georeferencing Strategy")
           scale_color_manual(values = colours)

p_bias_dv

ggsave(
  filename = glue(dir_figures, "p_bias_dv.pdf"),
  plot = p1, width = 12, height = 6
)

```




